# Analyse risque crédit

## Librairies

In [1]:
import pandas as pd
from src.data_quality import *
from src.data_analyse import *
from src.data_transformation import *

***
## Import des données
***

In [2]:
df_loans = pd.read_csv(r"data\raw\loan_portfolio.csv")
print(f"Dimensions du df : {df_loans.shape[0]} lignes et {df_loans.shape[1]} colonnes")
df_loans.head(10)

Dimensions du df : 50000 lignes et 24 colonnes

,loan_id,origination_date,maturity_date,maturity_months,sector,loan_type,collateral,initial_rating,credit_score,ead,...,pd_annual,lgd,el,unexpected_loss,rwa,defaulted,default_date,survival_months,recovery_rate,loss_given_default
0,L000001,2017-10-01,2019-10-01,24,Technology,mortgage,secured,B,704,1035611.99,...,0.041076,0.7858,33426.80,161508.03,442905.14,0,NaN,24,NaN,NaN
1,L000002,2016-06-01,2020-06-01,48,Healthcare,term_loan,unsecured,A,702,800786.92,...,0.000887,0.7034,499.82,16771.62,6622.66,0,NaN,48,NaN,NaN
2,L000003,2023-08-01,2024-12-31,36,Real_Estate,bond,secured,BBB,699,4327864.12,...,0.002622,0.5503,6243.54,121781.72,82726.94,0,NaN,36,NaN,NaN
3,L000004,2016-04-01,2024-12-31,120,Real_Estate,term_loan,secured,B,641,3810461.19,...,0.041679,0.3541,56237.33,269661.85,745144.64,0,NaN,120,NaN,NaN
4,L000005,2015-10-01,2019-10-01,48,Energy,bond,unsecured,CCC,597,2925538.53,...,0.136071,0.6576,261778.69,659614.05,3468567.58,0,NaN,48,NaN,NaN
5,L000006,2023-06-01,2024-12-31,36,Industrials,mortgage,secured,B,628,76645.49,...,0.041237,0.5772,1824.29,8796.50,24171.91,0,NaN,36,NaN,NaN
6,L000007,2019-12-01,2024-12-31,120,Retail,term_loan,unsecured,AA,828,732703.69,...,0.000427,0.6496,203.07,9829.30,2690.74,0,NaN,120,NaN,NaN
7,L000008,2018-12-01,2022-12-01,48,Retail,term_loan,secured,BBB,801,50000.00,...,0.002544,0.4838,61.53,1218.50,815.33,1,2020-04-01,16,0.5162,24190.00
8,L000009,2021-08-01,2023-08-01,24,Telecom,mortgage,secured,A,682,442881.00,...,0.000890,0.4484,176.74,5921.75,2341.80,0,NaN,24,NaN,NaN
9,L000010,2018-06-01,2020-06-01,24,Consumer,mortgage,secured,BBB,769,60656.97,...,0.002568,0.5130,79.91,1574.91,1058.87,1,2020-04-01,22,0.4870,31117.03

***
## Qualité de la donnée
***

In [3]:
dq = DataQuality() # Initialiser la class DataQuality

# Check le type des colonnes
dq.check_types(df_loans)

loan_id                   str
origination_date          str
maturity_date             str
maturity_months         int64
sector                    str
loan_type                 str
collateral                str
initial_rating            str
credit_score            int64
ead                   float64
coupon_rate           float64
leverage              float64
interest_coverage     float64
debt_to_equity        float64
pd_annual             float64
lgd                   float64
el                    float64
unexpected_loss       float64
rwa                   float64
defaulted               int64
default_date              str
survival_months         int64
recovery_rate         float64
loss_given_default    float64
dtype: object

In [4]:
dq.check_nulls(df_loans) # Check le nombre et % de valeurs nulles

               Colonne  Nombre de null  % de null
0              loan_id               0      0.000
1     origination_date               0      0.000
2        maturity_date               0      0.000
3      maturity_months               0      0.000
4               sector               0      0.000
5            loan_type               0      0.000
6           collateral               0      0.000
7       initial_rating               0      0.000
8         credit_score               0      0.000
9                  ead               0      0.000
10         coupon_rate               0      0.000
11            leverage               0      0.000
12   interest_coverage               0      0.000
13      debt_to_equity               0      0.000
14           pd_annual               0      0.000
15                 lgd               0      0.000
16                  el               0      0.000
17     unexpected_loss               0      0.000
18                 rwa               0      0.000
19           defaulted               0      0.000
20        default_date           43050      0.861
21     survival_months               0      0.000
22       recovery_rate           43050      0.861
23  loss_given_default           43050      0.861

Les colonnes "loss_given_default", "recovery_rate" et "default_date" ont des valeurs manquantes étant donné que ces colonnes sont uniquement calculées pour les crédit comme étant en défaut. Elles ne seront donc pas utilisées pour la prédiction d'un défaut mais seront utiliser pour l'analyse descriptive du jeu de données.

In [5]:
dq.check_unique_values(df_loans)

Nombre de lignes totales : 50000
Nombre de lignes uniques : 50000
Nombre de lignes dupliquées : 0

In [6]:
dq.check_unique_values(df_loans, cols = ['loan_id'])

Nombre de lignes totales : 50000
Nombre de lignes uniques : 50000
Nombre de lignes dupliquées : 0

In [7]:
date_cols = dq.check_date_format(df_loans)

Colonnes ayant des données au format de date

            Colonne Cohérence sur lignes valides  Total lignes
0  origination_date                  50000/50000         50000
1     maturity_date                  50000/50000         50000
2      default_date                    6950/6950         50000

***
## Transformation des données pour analyse
***

In [8]:
dt = DataTransformation()

df_loans['origination_date'] = dt.set_datetime_type(df_loans['origination_date'])
df_loans['maturity_date'] = dt.set_datetime_type(df_loans['maturity_date'])
df_loans['default_date'] = dt.set_datetime_type(df_loans['default_date'])

display(df_loans[['origination_date', 'maturity_date', 'default_date']].head(10))

  origination_date maturity_date default_date
0       2017-10-01    2019-10-01          NaT
1       2016-06-01    2020-06-01          NaT
2       2023-08-01    2024-12-31          NaT
3       2016-04-01    2024-12-31          NaT
4       2015-10-01    2019-10-01          NaT
5       2023-06-01    2024-12-31          NaT
6       2019-12-01    2024-12-31          NaT
7       2018-12-01    2022-12-01   2020-04-01
8       2021-08-01    2023-08-01          NaT
9       2018-06-01    2020-06-01   2020-04-01

In [9]:
dq.check_types(df_loans[['origination_date', 'maturity_date', 'default_date']])

origination_date    datetime64[us]
maturity_date       datetime64[us]
default_date        datetime64[us]
dtype: object

***
## Analyse des données
***

- Aperçu général des statistiques

In [10]:
da = DataAnalyse()
df_stats_num = da.analyse_var_numeriques(df_loans)
df_stats_num

Analyse des variables numériques :
maturity_months, credit_score, ead, coupon_rate, leverage, interest_coverage, debt_to_equity, pd_annual, lgd, el, unexpected_loss, rwa, defaulted, survival_months, recovery_rate, loss_given_default

,moyenne,quantile 25%,mediane (50%),quantile 75%,maximum,minimum,etendue,somme,variance,ecart type
maturity_months,53.97,36.00,48.00,60.00,1.200000e+02,12.00,1.080000e+02,2.698524e+06,7.137600e+02,26.72
credit_score,714.98,679.00,715.00,750.00,8.500000e+02,518.00,3.320000e+02,3.574913e+07,2.590140e+03,50.89
ead,3298604.67,548268.50,1389712.02,3425439.33,3.611778e+08,50000.00,3.611278e+08,1.649302e+11,4.438149e+13,6661943.36
coupon_rate,3.08,2.36,3.06,3.74,7.530000e+00,1.00,6.530000e+00,1.539544e+05,1.220000e+00,1.10
leverage,6.91,4.06,6.08,9.07,1.500000e+01,0.50,1.450000e+01,3.456889e+05,1.359000e+01,3.69
interest_coverage,3.76,2.37,3.31,4.65,2.000000e+01,0.50,1.950000e+01,1.882045e+05,4.060000e+00,2.01
debt_to_equity,2.09,1.03,1.65,2.64,1.000000e+01,0.10,9.900000e+00,1.045442e+05,2.470000e+00,1.57
pd_annual,0.02,0.00,0.00,0.02,2.400000e-01,0.00,2.400000e-01,1.123070e+03,0.000000e+00,0.04
lgd,0.55,0.44,0.54,0.65,9.800000e-01,0.09,8.900000e-01,2.732580e+04,2.000000e-02,0.14
el,38475.72,787.53,3587.83,18560.52,6.411410e+06,3.60,6.411406e+06,1.923786e+09,2.530647e+10,159080.08
unexpected_loss,181560.53,17207.46,52059.94,155943.00,2.239212e+07,273.53,2.239185e+07,9.078027e+09,2.467063e+11,496695.35
rwa,509803.30,10434.81,47538.74,245926.91,8.495118e+07,47.65,8.495114e+07,2.549017e+10,4.442867e+12,2107811.05
defaulted,0.14,0.00,0.00,0.00,1.000000e+00,0.00,1.000000e+00,6.950000e+03,1.200000e-01,0.35
survival_months,49.12,36.00,48.00,60.00,1.200000e+02,1.00,1.190000e+02,2.456231e+06,7.238200e+02,26.90
recovery_rate,0.45,0.35,0.46,0.56,8.600000e-01,0.02,8.400000e-01,3.159210e+03,2.000000e-02,0.15
loss_given_default,1713656.67,291571.93,719818.22,1750271.71,1.113264e+08,14330.00,1.113121e+08,1.190991e+10,1.304792e+13,3612190.34

In [11]:
da.analyse_var_temporelles(df_loans)

Analyse des variables temporelles :

Statistiques de la variable temporelle :  origination_date
count                         50000
mean     2019-06-14 18:01:09.120000
min             2015-01-01 00:00:00
25%             2017-03-01 00:00:00
50%             2019-07-01 00:00:00
75%             2021-09-01 00:00:00
max             2023-12-01 00:00:00
Name: origination_date, dtype: object
Intervalle de temps des données de la colonnes origination_date : 8 années, 11 mois, et 6 jours

Statistiques de la variable temporelle :  maturity_date
count                         50000
mean     2023-01-08 05:26:09.600000
min             2016-01-01 00:00:00
25%             2021-05-01 00:00:00
50%             2023-11-01 00:00:00
75%             2024-12-31 00:00:00
max             2024-12-31 00:00:00
Name: maturity_date, dtype: object
Intervalle de temps des données de la colonnes maturity_date : 9 années, 0 mois, et 2 jours

Statistiques de la variable temporelle :  default_date
count                          6950
mean     2021-03-25 01:09:37.035971
min             2015-02-01 00:00:00
25%             2020-04-01 00:00:00
50%             2020-06-01 00:00:00
75%             2022-07-01 00:00:00
max             2033-09-01 00:00:00
Name: default_date, dtype: object
Intervalle de temps des données de la colonnes default_date : nan années, nan mois, et nan jours